import {Geist, Geist_Mono} from "next/font/google";
import "../globals.css";
import HeaderPage from "@/app/(client)/components/header";
import FooterPage from "@/app/(client)/components/footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Creative Homes | Make Yours house  ",
	description: "Generated by create next app",
};

export default function RootLayout({children}) {
	return (
		<html lang="en">
		<body
			className={`${geistSans.variable} ${geistMono.variable} antialiased`}
		>
		<HeaderPage/>
		{children}
		<FooterPage/>
		</body>
		</html>
	);
}
