import { NextResponse } from "next/server";
import Project from "@/models/Project";
import Client from "@/models/Client";
import Contractor from "@/models/Contractor";
import ProjectType from "@/models/ProjectType";
import "@/lib/db";

export async function GET() {
	try {
		const projects = await Project.findAll({
			include: [
				{ model: Client, as: "client", attributes: ["id", "name", "email", "clientId"] },
				{ model: Contractor, as: "contractor", attributes: ["id", "name", "email", "contractorId"] },
				{ model: ProjectType, as: "projectType", attributes: ["id", "name"] },
			],
			order: [["createdAt", "ASC"]],
		});

		return NextResponse.json({ success: true, projects });
	} catch (error) {
		console.error("PROJECT GET ERROR =>", error);
		return NextResponse.json({ success: false, error: error.message }, { status: 500 });
	}
}

export async function POST(req) {
	try {
		const body = await req.json();

		if (!body.title || !body.clientId || !body.contractorId || !body.projectTypeId) {
			return NextResponse.json(
				{ success: false, error: "Title, clientId, contractorId, projectTypeId required" },
				{ status: 400 }
			);
		}

		// 🆕 projectUid automatically generated by Model

		const project = await Project.create({
			title: body.title,
			description: body.description,
			status: "pending_approval",
			startDate: body.startDate,
			endDate: body.endDate,
			totalCost: body.totalCost,
			clientId: Number(body.clientId),
			contractorId: Number(body.contractorId),
			projectTypeId: Number(body.projectTypeId),

			clientApproved: false,
			contractorApproved: false,
			adminLocked: false,
		});

		return NextResponse.json({ success: true, project });
	} catch (error) {
		console.error("PROJECT CREATE ERROR =>", error);
		return NextResponse.json({ success: false, error: error.message }, { status: 500 });
	}
}
